import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "@/components/ThemeProvider/theme-provider";
import Header from "@/components/Header/header";

export const metadata: Metadata = {
  title: "Kanban Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Header/>
           {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
